# Generated by Django 2.2 on 2019-07-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_member',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=11)),
                ('level', models.CharField(max_length=1)),
                ('reg_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='diary',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50)),
                ('dogda_name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('reg_date', models.DateField()),
                ('flowers', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
                ('reg_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dogda_vaccination_info',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50)),
                ('dogda_name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('vaccination_date', models.CharField(max_length=8)),
                ('reg_date', models.DateField()),
            ],
            options={
                'unique_together': {('id', 'dogda_name', 'type', 'vaccination_date')},
            },
        ),
        migrations.CreateModel(
            name='dogda_info',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50)),
                ('dogda_name', models.CharField(max_length=20)),
                ('dogda_birth', models.CharField(max_length=8)),
                ('dogda_gender', models.CharField(max_length=1)),
                ('reg_date', models.DateField()),
            ],
            options={
                'unique_together': {('id', 'dogda_name')},
            },
        ),
    ]
