# Generated by Django 2.2 on 2019-07-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogda_info',
            name='dogda_type',
            field=models.CharField(default='charField', max_length=20),
        ),
    ]
