# Generated by Django 2.2 on 2019-07-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_dogda_info_dogda_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogda_info',
            name='dogda_type',
            field=models.CharField(max_length=20),
        ),
    ]
