# Generated by Django 2.2 on 2019-07-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_notice_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(),
        ),
    ]
