# Generated by Django 2.2 on 2019-07-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20190715_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='flowers',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
