# Generated by Django 2.2 on 2019-09-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20190716_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='idx',
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
